### PR TITLE
Switch from flag to kingpin fixes #173

### LINKED ISSUE #173: Switch from flag to kingpin
Hi @zwopir,

This is issue is a reminder for switching to [kingpin](https://github.com/alecthomas/kingpin) as many other exporter does.

As a breaking change, this should be done shortly before a breaking change release.

### PR DESCRIPTION
**Pull request by TheMeier**
As discussed in #173 this is a breaking change.

### CODE REVIEW

**Comment by zwopir** [comment]
Hi @TheMeier,

thanks for your PR. There's another breaking change in the pipeline (#165). Can you add the port change to your PR?

I can then create a RC with the pending new features and the breaking change together

**Comment by TheMeier** [comment]
@zwopir will do ;)

**Comment by TheMeier** [comment]
@zwopir any news on this? How about a release..?

**Comment by zwopir** [comment]
had pretty much to do the last week, but yes. I try to make a release this week

**Comment by TheMeier** [comment]
@zwopir any news on the release topic?

**Pull request merged**
