### PR TITLE
feat: added task_max_waiting_in_queue_millis

### PR DESCRIPTION
**Pull request by caarlos0**
I think this can be useful to check if the cluster is slowing down :)

### CODE REVIEW

**Comment by caarlos0** [comment]
ping @zwopir

**Comment by zwopir** [comment]
Thanks, @caarlos0 !

**Comment by caarlos0** [comment]
@zwopir any ETA for the next release? Can I help with anything?

**Comment by zwopir** [comment]
I'm planning a new release for the next week. There are a few pending PRs I'd like to put into the release

**Comment by caarlos0** [comment]
Great, let me know if I can help with anything. I'm using this in production, and it is a great project, so it is only fair that I spend some time helping to evolve it :)

**Pull request merged**
