### PR TITLE
Add filesystem IO metrics

### PR DESCRIPTION
**Pull request by seanlaff**
Filesystem IO metrics are in the elasticsearch nodestats output, but they were not being exported.

In addition to the new IO metrics, the filesystem `data` metrics have had their variables renamed to avoid confusion. In elastic <5 the only metric within the filesystem output of nodeStats  was `data`, which is why I assume the naming was less specific. In elastic >5 the filesystem output of nodeStats contains both `data` as well as `io_stats`.

### CODE REVIEW

**Comment by zwopir** [comment]
Hi @seanlaff,

thanks for your contribution! Looks good. Can you fix the conflict so I can merge your PR?!

**Comment by caarlos0** [comment]
I usually run node_exporter on the ES nodes as well... isn't it better to just use the node_exporter IO-related metrics?

**Comment by zwopir** [comment]
I agree the node_exporter provides the more detailed set of metrics. The argument for having os related metrics in the exporter is mainly that you are usually not able to install the node_exporter in hosted es (by was or elastic for example)

**Comment by caarlos0** [comment]
> I agree the node_exporter provides the more detailed set of metrics. The argument for having os related metrics in the exporter is mainly that you are usually not able to install the node_exporter on hosted es (by was or elastic for example)

hmm, that makes sense indeed.

**Comment by seanlaff** [comment]
@zwopir Resolved the conflicts. Thanks for taking a look

**Comment by zwopir** [comment]
thanks again for your contribution!

**Pull request merged**
