### PR TITLE
Further health metrics v2

### PR DESCRIPTION
**Pull request by jmcarp**
Cleanup based on code review of #36.

### CODE REVIEW

**Comment by jmcarp** [comment]
@dominikschulz: would you mind cutting a new release with binaries now that this is merged?

**Comment by dominikschulz** [comment]
Released 0.3.2 right now. Docker image is up, will build linux binaries later.

**Comment by jmcarp** [comment]
Thanks! Just one question: it looks like the binaries for release 0.3.2 are named 0.3.1. Can you confirm that they actually contain the code for release 0.3.2?

**Comment by dominikschulz** [comment]
Sorry, that was a mistake. There should be properly named binaries available now.

**Pull request merged**
