### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by 0x46616c6b**

### CODE REVIEW

**Comment by 0x46616c6b** [comment]
This could be the release chain

    docker run -it --rm -v $PWD:/go/src/github.com/ewr/elasticsearch_exporter -w /go/src/github.com/0x46616c6b/elasticsearch_exporter --net=host golang:1.4 make
    docker build --rm --force-rm -t ewr/elasticsearch_exporter:latest .
    #docker push ewr/elasticsearch_exporter:latest

**Comment by flecno** [comment]
i'm really new in the go universe. But I can't build the image when i follow your instructions:

If I run your build step it will fails for me. How I can get the dependencies first?

```
$ docker run -it --rm -v $PWD:/go/src/github.com/ewr/elasticsearch_exporter -w /go/src/github.com/ewr/elasticsearch_exporter golang:1.4 make
mkdir -p /go/src/github.com/ewr/elasticsearch_exporter/.build/gopath/src/github.com/prometheus/
ln -s /go/src/github.com/ewr/elasticsearch_exporter /go/src/github.com/ewr/elasticsearch_exporter/.build/gopath/src/github.com/prometheus/elasticsearch_exporter
GOROOT=/usr/src/go GOPATH=/go/src/github.com/ewr/elasticsearch_exporter/.build/gopath /usr/src/go/bin/go build  -o elasticsearch_exporter
elasticsearch_exporter.go:15:2: cannot find package "github.com/prometheus/client_golang/prometheus" in any of:
	/usr/src/go/src/github.com/prometheus/client_golang/prometheus (from $GOROOT)
	/go/src/github.com/ewr/elasticsearch_exporter/.build/gopath/src/github.com/prometheus/client_golang/prometheus (from $GOPATH)
Makefile.COMMON:95: recipe for target 'elasticsearch_exporter' failed
make: *** [elasticsearch_exporter] Error 1
```

**Comment by flecno** [comment]
And I also would not use ubuntu as base image. We don't need ubuntu here. We already want to ship a static compiled program, or I'm wrong? Perhaps we should depend on `sdurrheimer/alpine-golang-make-onbuild` or something else. I try to build this project in `sdurrheimer/alpine-golang-make-onbuild` but it fails with the same error.

**Comment by akosveres** [comment]
Hi guys,

I managed to create a docker image with the help of the guys from #prometheus (big up!)

```
FROM golang:alpine

ADD . /go/src/github.com/0x46616c6b/elasticsearch_exporter
RUN export GO15VENDOREXPERIMENT=1
RUN apk add --update git \
        && go get github.com/0x46616c6b/elasticsearch_exporter \
        && rm -rf /var/cache/apk/*

EXPOSE 9108

ENTRYPOINT ["elasticsearch_exporter"]

CMD ["-es.uri=http://example.com", "--es.all=true", "--web.listen-address=:9108", "--web.telemetry-path=/metrics"]
```

**Comment by 0x46616c6b** [comment]
@akosveres seems to be the better solution. i will change the PR.

**Comment by 0x46616c6b** [comment]
I would like to integrate the Makefile in the Docker build but at the moment its not working properly.

**Comment by dominikschulz** [comment]
Added an up to date version of the Dockerfile in #28

**Comment by dominikschulz** [comment]
This was obliterated by #28. Closing.

**Pull request closed without merging**
