### PR TITLE
Build and push docker image automatically

### PR DESCRIPTION
**Pull request by tback**
- ignore go tip for now

addresses: https://github.com/justwatchcom/elasticsearch_exporter/issues/26

TODO:
create a repository on quay
create a robot user for that repository on quay, copy the docker login path
```
travis env set DOCKER_USERNAME <quay_io_robot_username>
travis env set DOCKER_PASSWORD <quay_io_robot_password>
travis env set DOCKER_IMAGE_NAME quay.io/<organisation>/elasticsearch_exporter
```

### CODE REVIEW

**Comment by tback** [comment]
Checks are failing because travis needs to set the three environment variables above.

**Comment by tback** [comment]
Hey @dominikschulz, can I do anything to get this merged?

**Comment by lhoss** [comment]
Just made the connection between my last comment in #26  and this PR..

👍  to get this merged, and so hopefully get a public docker image of the latest tag (0.3.1) in @dominikschulz 's repos: https://quay.io/repository/traum-ferienwohnungen/elasticsearch_exporter/

ps: @dominikschulz: I saw your latest image is tagged 0.5.0.
Wouldn't it be much nicer to follow the elasticsearch_exporter tags?
and in case you would have many builds for the same exporter tag, just extend the version string for ex like: 0.3.1-${build/commit-id}

**Comment by tback** [comment]
I'm also interested to merge what we changed.

Regarding our increased version numbers and changes: We added functionality, so it seemed natural to increase the version number. I know the changes are small, but so is this project.

We'd be happy to contribute back and unfork the project.

/cc @dominikschulz

**Comment by lhoss** [comment]
Forgot to ask: 

> We added functionality, so it seemed natural to increase the version number. I know the changes are small, but so is this project.

I agree you should have some version increase , just IMO my proposed '2 dimensional' version scheme (with 1.dim containing the orig. component version, the 2.dim for your choosing) has 2  advantages:
* you can immediately see the exporter version contained in the docker image
* you can naturally stay in sync with the upstream/original repos, once a new version (0.3.2 for ex) comes out

Anyway, I forgot to ask, that latest 0.5.0 build, which `elasticsearch_exporter`tag (or commit) does it finally contain ?  ( is there an easy way to see this in the quai.io UI?  also too bad one can't see the Dockerfile used )

**Pull request closed without merging**
